name: casper_dart_sdk
description: Dart Casper Client SDK
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  asn1lib: ^1.1.0
  build_runner: ^2.1.11
  dart_bignumber:
    git: https://github.com/hoangkianh/dart-bignumber.git
  duration: ^3.0.11
  ecdsa: ^0.0.4
  hdkey: ^0.0.1
  http: ^0.13.4
  json_serializable: ^6.2.0
  oxidized: ^5.2.0
  pinenacl: ^0.3.4
  secp256k1: ^0.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.5
